/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20 from "./ERC20";
export { WorkerRegistration__factory } from "./WorkerRegistration__factory";
export { TSQD__factory } from "./TSQD__factory";
