name: docker
on:
  workflow_dispatch: # manually run
    inputs:
      tag:
        description: image tag
        required: true

env:
  CI: true

jobs:
  publish:
    name: Build & publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: cd packages/contracts

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & publish playground image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: packages/contracts
          file: packages/contracts/Dockerfile-playground
          tags: subsquid/playground:${{ inputs.tag }}
