name: Build reclaim image
on:
  workflow_dispatch: # manually run
    inputs:
      tag:
        description: image tag
        required: true

env:
  CI: true

jobs:
  publish:
    name: Build & publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - run: cd packages/contracts

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & publish contracts image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: packages/contracts
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8,windows/amd64
          file: packages/contracts/Dockerfile-reclaimFunds
          tags: subsquid/reclaim:latest
